apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-hostpath-pv
  labels:
    type: local
spec:
  storageClassName: sc-db
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres