apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-service
  name: postgres-service
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    name: postgres-node
  type: LoadBalancer