apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: rails-node
  name: rails-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: rails-node
    spec:
      containers:
      - image: gcr.io/book-management-220011/book_management_rails:v0.1
        name: rails-node
        ports:
        - containerPort: 3000