apiVersion: v1
kind: Service
metadata:
  labels:
    name: rails-service
  name: rails-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: rails-node
  type: LoadBalancer